setono_sylius_redirect:
    form:
        errors:
            source_already_existing: 'Il y a déjà une redirection ayant pour source "{{ source }}". ID de la redirection : {{ conflictingIds }}'
